addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

# new options suggested by Alexandre Fayolle
# sudo: false
cache: pip

python:
  - "2.7"

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  - TRANSIFEX_ORGANIZATION='adhoc'
  # to get secure, run 'travis encrypt TRANSIFEX_PASSWORD=[transifex_password] -r [github_repo]'
  # example of github repo 'ingadhoc/odoo-infrastructure'
  - secure: MsuVhrdOSs2oqPP+odFpKVehX6RlS8nJRXKm9mzE+HCxpR8su1HCrVMpsgBMFUkHAvTQIt5UPvOaBl1Pi2A6hPDTlervdTRhDRRRzXeNfe2+rb6+DevOB0fqbGLo39dg/VO0QwXtrVUzLIPkrrop/QiBBhuDB4TI84qEkRKbVLz4oS/Jj4eI7mRf0jmQ98scE0M1nXqE4KhEP8bPAJ7OWMkXbXonqZ1NGrwZI+bMKFDZHNidUiyGAcvsLqk6r/PcfySLHbYyR06QImvZXWGyx9XDYhP6c19yFhTi8OdFYWw9eglWSKkdvkxrqKh5gIToIiPOa49vq5Vr7Gzn0cJkx0Z9TlhjVdD2Yn5JBO8ymiuWSI70gYL8dPMa7tFp169u33Fd3GHi29q+T1CJF37A/5PPEAHgfMcbP5LxvJXdS7ZOFXBKwgmO8hDg6BX+uowN/2EGyaTIdiaEA+N2He0VHFYACtdh2f8m9zCVozH60kXmbfSeUzT6CMPFL6ridOTQ4QmUbCNSypgS3MSHA4qrO90G+I2ye3y92xlCLbOie34Pny4lbHuwfUzaCf2ZP4iysPIcf4NyCPqKOvWj2t4RJtKi8DvkcWtWYfjsJm7h8vkUiITtwnmQ1hPmBx1Ys8rt4L7loHOQ4QUV8MPYIPi/nxXixYc0V4wNfv6AAcz+lo8=

  matrix:
  # TODO enable lint check
  #- LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  # we install libcups2-dev here because it is not on travis whitelist so it is not installable by addons/apt/packages
  # you can check if available on https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcups2-dev
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git -b 8.0 ${HOME}/odoo-addons

  # repository requirements
  - pip install -r requirements.txt

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
